services:
    net-app-dev:
        container_name: transaction-backend-container
        build:
            context: .
            dockerfile: back-end-api/Dockerfile.dev
        env_file: back-end-api/.env
        environment:
            DEVELOPMENT: true
            ASPNETCORE_HTTP_PORTS: 8080
            ASPNETCORE_ENVIRONMENT: Development
            DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "1"
            POSTGRES_HOST: db-dev
            POSTGRES_PORT: 5432
            POSTGRES_LOGIN: ${DATABASE_LOGIN}
            POSTGRES_PASSWD: ${DATABASE_PASSWD}
            POSTGRES_DB: ${DATABASE_DB}
        ports:
            - "${ASP_PORT}:8080"
        networks:
            - transaction-network
        volumes:
            - ./back-end-api:/app
        tty: true
        command: dotnet watch run

    node-app-dev:
        container_name: node-frontend-container
        build:
            context: .
            dockerfile: node-front-end/Dockerfile
        environment:
            IS_DEVELOPMENT: true
        ports:
            - "${NODE_PORT}:8080"
        networks:
            - transaction-network
        tty: true
        command: npm run dev

    db-dev:
        container_name: postgres-db-container
        build:
            context: .
            dockerfile: postgres-db/Dockerfile
        environment:
            POSTGRES_USER: ${DATABASE_LOGIN}
            POSTGRES_PASSWORD: ${DATABASE_PASSWD}
            POSTGRES_DB: ${DATABASE_DB}
        ports:
            - "${DB_PORT}:5432"
        networks:
            - transaction-network
        tty: true

networks:
    transaction-network: {}

