version: '3'

services:
    app:
        container_name: trn-backend-container
        build:
            context: .
            dockerfile: back-end-api/Dockerfile
        ports:
            - "5000:8080"
        networks:
            - transaction-network
        tty: true
    db:
        container_name: postgres-db-container
        #user: postgres
        environment:
            POSTGRES_USER: master
            # Password for testing purposes only. Do NOT use in production.
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: main
        build:
            context: .
            dockerfile: postgres-db/Dockerfile
        ports:
            - "5100:5432"
        networks:
            - transaction-network
        tty: true

networks:
    transaction-network:
        name: trn-network
        external: false