services:
    asp-app:
        container_name: trn-backend-container
        build:
            context: .
            dockerfile: back-end-api/Dockerfile
        ports:
            - "${ASP_PORT}:8080"
        networks:
            - transaction-network
        tty: true
    node-app:
        container_name: node-frontend-container
        environment:
            # Secret for testing purposes only. Do NOT use in production.
            SESSION_SECRET: km9uGbhByLUY4gczAeWPqf
        build:
            context: .
            dockerfile: node-front-end/Dockerfile
        ports:
            - "${NODE_PORT}:8080"
        networks:
            - transaction-network
        tty: true
    db:
        container_name: postgres-db-container
        #user: postgres
        environment:
            POSTGRES_USER: master
            # Password for testing purposes only. Do NOT use in production.
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: main
        build:
            context: .
            dockerfile: postgres-db/Dockerfile
        ports:
            - "${DB_PORT}:5432"
        networks:
            - transaction-network
        tty: true

networks:
    transaction-network:
        name: trn-network
        external: false