
--- PostgresSQL database start

--- Create the users table

CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME TEXT NOT NULL,
	FULLNAME TEXT NOT NULL,
	MAIL TEXT NOT NULL,
	SECRET TEXT NOT NULL,
	CREATEDAT DATE NOT NULL,
	ROLE TEXT NOT NULL
);

--- Insert some pre-fabricated users

INSERT INTO USERS (NAME, FULLNAME, SECRET, MAIL, CREATEDAT, ROLE)
VALUES ('admin', 'Admin', '123', 'transaction.app@mail.com', CURRENT_DATE, 'Admin');

INSERT INTO USERS (NAME, FULLNAME, SECRET, MAIL, CREATEDAT, ROLE)
VALUES ('Yozef', 'Yozef Baruch', 'yozefb27', 'yozefb@mail.com', CURRENT_DATE, 'User');

INSERT INTO USERS (NAME, FULLNAME, SECRET, MAIL, CREATEDAT, ROLE)
VALUES ('Robert', 'Robert Ervin', 'reh1906', 'reh@mail.com', CURRENT_DATE, 'User');

INSERT INTO USERS (NAME, FULLNAME, SECRET, MAIL, CREATEDAT, ROLE)
VALUES ('Lea', 'Lea Adonis', 'ladonis1996', 'leadonis@mail.com', CURRENT_DATE, 'User');

--- Create the transaction history table

CREATE TABLE TRANSACTION_HISTORY (
	ID SERIAL PRIMARY KEY,
	ORIGINUSER_ID INTEGER NOT NULL,
	DESTINEDUSER_ID INTEGER NOT NULL,
	CREATEDAT DATE NOT NULL,
	AMOUNT FLOAT NOT NULL
);

--- Base transaction

INSERT INTO TRANSACTION_HISTORY (ORIGINUSER_ID, DESTINEDUSER_ID, CREATEDAT, AMOUNT)
VALUES (2, 3, CURRENT_DATE, 26.87)
